package nextstep.signup.domain

enum class ErrorCode {
    ERROR_USERNAME_LENGTH,
    ERROR_USERNAME_INVALID_CHARACTERS,
    ERROR_INVALID_EMAIL_FORMAT,
    ERROR_PASSWORD_LENGTH,
    ERROR_PASSWORD_REQUIREMENTS,
    ERROR_PASSWORD_MISMATCH,
}
